### ISSUE TITLE
dzen.ru/video/watch/ is broken 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardExtra#543]
### Prerequisites

- [X] Filters were updated before reproducing an issue
- [X] AdGuard Extra version is up-to-date
- [X] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard for Android

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Where is the problem encountered?

https://dzen.ru/video/watch/63d6ade35cb2855850a22092

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Issue Details

Steps to reproduce:
1. Open https://dzen.ru/video/watch/63d6ade35cb2855850a22092
https://github.com/AdguardTeam/AdguardFilters/issues/189218#issuecomment-2378506390

Temporaty fixed by `@@||dzen.ru/video/watch/$extension="AdGuard Extra"|"AdGuard Extra (Beta)"` in the Base filter.

**TODO:** remove it after fixing.

### Expected Behavior

Page is not broken.

### Actual Behavior

Page is broken.

### Screenshots

in the issue

### Privacy

- [X] I agree to follow this condition
